# Generated by Django 4.1 on 2022-09-27 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_hzte', models.CharField(max_length=6, unique=True, verbose_name='codigo horizonte')),
                ('tipologia', models.CharField(choices=[('E', 'Compacta'), ('D', 'Basica'), ('C', 'Economica'), ('CE', 'Economica en esquina'), ('B', 'Standard'), ('BE', 'Standar en esquina'), ('A', 'Mejorada')], max_length=2)),
                ('lote', models.CharField(choices=[('LE', 'Tamaño estandar'), ('LAM', 'Tamaño ampliado')], default='LE', max_length=3)),
                ('ambientes', models.CharField(choices=[('MO', 'Monoambiente'), ('01', '1 Dormitorio'), ('02', '2 Dormitorios'), ('03', '3 Dormitorios')], max_length=2)),
                ('vigente', models.BooleanField(default=True)),
                ('gastos_administrativos', models.DecimalField(decimal_places=6, default=0.0007, max_digits=7)),
                ('puntos', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='puntos para adjudicar')),
            ],
        ),
        migrations.CreateModel(
            name='ValorActualizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_valor', models.DateField(default=datetime.date(2022, 9, 26))),
                ('valor_actualizado', models.PositiveIntegerField()),
                ('cod_hzte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadoraAdjudicacion.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPorAdjudicar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odm', models.DecimalField(decimal_places=2, default=0.84, max_digits=3)),
                ('oferta_efectivo', models.PositiveIntegerField(default=0)),
                ('oferta_treinta', models.PositiveIntegerField(default=0)),
                ('oferta_sesenta', models.PositiveIntegerField(default=0)),
                ('oferta_noventa', models.PositiveIntegerField(default=0)),
                ('oferta_c_veinte', models.PositiveIntegerField(default=0)),
                ('oferta_c_cincuenta', models.PositiveIntegerField(default=0)),
                ('oferta_c_ochenta', models.PositiveIntegerField(default=0)),
                ('vivienda_adjudicar', models.ForeignKey(limit_choices_to={'vigente': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadoraAdjudicacion.vivienda', to_field='cod_hzte')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiguedad', models.PositiveIntegerField()),
                ('cancelado', models.DecimalField(decimal_places=4, max_digits=7)),
                ('deuda', models.PositiveIntegerField(default=0)),
                ('vivienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadoraAdjudicacion.vivienda', to_field='cod_hzte')),
            ],
        ),
    ]
