# Generated by Django 4.1 on 2022-10-05 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraAdjudicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoractualizado',
            name='fecha_valor',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
    ]
