# Generated by Django 4.1 on 2022-11-15 00:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraAdjudicacion', '0002_alter_valoractualizado_fecha_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planporadjudicar',
            name='vivienda_adjudicar',
            field=models.ForeignKey(limit_choices_to={'vigente': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadoraAdjudicacion.vivienda'),
        ),
        migrations.AlterField(
            model_name='valoractualizado',
            name='fecha_valor',
            field=models.DateField(default=datetime.date(2022, 11, 14)),
        ),
    ]
